#! /bin/sh

# SXHKD - Keybindings
pgrep -x sxhkd > /dev/null || sxhkd &

# Polybar
$HOME/.config/polybar/launch.sh

# Workspaces
bspc monitor -d 爵      


# Gaps and Borders
bspc config border_width         1
bspc config window_gap          12

bspc config focused_border_color "#478061"
bspc config normal_border_color "#222222"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Window Rules
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Nitrogen state=floating
bspc rule -a Gpick state=floating
bspc rule -a Toolkit state=floating

# Autostart
devmon &
setxkbmap de &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
picom -fc &
udiskie -At &
